### PR TITLE
Change user agent as filmon was blocking old one

### PR DESCRIPTION
**Pull request by mcaptur**

### CODE REVIEW

**Comment by Mike-KL** [comment]
Please can this be tested and merged as pvr.filmon broken otherwise.
Can then close raised issue https://github.com/kodi-pvr/pvr.filmon/issues/55

**Comment by ksooo** [comment]
@mcaptur please bump the add-on version and update the changelog. Thanks.

**Comment by mcaptur** [comment]
Done

**Comment by ksooo** [comment]
And now please squash down the commits to a single commit and we're ready to go. ;-)

**Comment by Aristogiton** [comment]
Let me say that the use of a single #define (in FilmonAPI.cpp) would improve the maintainability of the software

**Comment by mcaptur** [comment]
done

**Comment by ksooo** [comment]
@mcaptur thanks

**Pull request merged**
