### PR TITLE
update to GetChannelStreamProperties()

### PR DESCRIPTION
**Pull request by fuzzard**
Logic was wrong in the initial implementation
I believe this should simplify it and also correct it.

### CODE REVIEW

**Comment by ksooo** [comment]
This actually looks better. TBH, I was not sure about correctness when I was seeing the initial version but was to lazy to actually drill into it deeper. Sorry for that. :-/

**Comment by ksooo** [comment]
So, ready to merge?

**Comment by fuzzard** [comment]
I believe so.

**Comment by ksooo** [comment]
:-)

**Comment by ksooo** [comment]
Let's give it a go. I'm sure there will be testers telling us quickly if we broke shit.

**Pull request merged**
